CREATE DATABASE minitask3;
SELECT current_database();

CREATE TABLE Categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Bookshelves (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Staffs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Books (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    category_id INT NOT NULL,
    bookshelf_id INT NOT NULL,

    FOREIGN KEY (category_id) REFERENCES Categories(id),
    FOREIGN KEY (bookshelf_id) REFERENCES Bookshelves(id)
);

ALTER TABLE Books
ADD created_at TIMESTAMP DEFAULT NOW() NOT NULL,
ADD updated_at TIMESTAMP;

CREATE TABLE Borrows (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_name VARCHAR(255) NOT NULL,
    book_id INT NOT NULL,
    staff_id INT NOT NULL,

    FOREIGN KEY (book_id) REFERENCES Books(id),
    FOREIGN KEY (staff_id) REFERENCES Staffs(id)
);

ALTER TABLE Borrows
ADD created_at TIMESTAMP DEFAULT NOW() NOT NULL,
ADD updated_at TIMESTAMP;

INSERT INTO Categories (name)
VALUES ('Fantasy'), ('Romance'), ('Mystery'), ('Thriller'), ('Science'), ('Historical'), ('Young Adult'), ('Self Help'), ('Biography'), ('Horror');

INSERT INTO Bookshelves (name)
VALUES ('Bookshelves 1'), ('Bookshelves 2');

INSERT INTO Staffs (name)
VALUES ('Andi'), ('Kuyang');

INSERT INTO Books (title, publisher, category_id, bookshelf_id)
VALUES
    ('Filosofi Kopi', 'GagasMedia', 1, 1),
    ('Bumi Manusia', 'Lentera Dipantara', 6, 1),
    ('Laskar Pelangi', 'Bentang Pustaka', 1, 1),
    ('Atomic Habits', 'Gramedia', 8, 1),
    ('Sapiens', 'Harvil Secker', 6, 1),
    ('Harry Potter', 'Bloomsbury', 1, 2),
    ('Rich Dad Poor Dad', 'Plata Publishing', 8, 2),
    ('Dylan 1990', 'Pastel Books', 7, 2),
    ('Kamus Inggris-Indo', 'Oxford University', 8, 2),
    ('Panduan Python', 'O Reilly Media', 5, 2);

INSERT INTO Borrows (borrower_name, book_id, staff_id)
VALUES
    ('Naufal', 1, 1),
    ('Vando', 2, 1),
    ('Ali', 3, 1),
    ('Ilham', 4, 1),
    ('Muftin', 5, 1),
    ('Angga', 6, 2),
    ('Dwiki', 7, 2),
    ('Hanif', 8, 2),
    ('Akmal', 9, 2),
    ('Aqil', 10, 2);

table Categories;
table Bookshelves;
table Staffs;
table Books;
table Borrows;