CREATE DATABASE example;
SELECT current_database();

CREATE TABLE Products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price INT
);

INSERT INTO Products (name, price)
VALUES
    ('Kambing', 600),
    ('Laptop', 1000),
    ('Liptip', 1000),
    ('Mouse', 50),
    ('Keyboard', 200);

table Products;

SELECT MAX(price) FROM Products;

SELECT name, price
FROM Products
WHERE price = (
        SELECT MAX(price)
        FROM Products
    );

SELECT name, price
FROM Products
WHERE price > (
    SELECT AVG(price)
    FROM Products
);

-- transactions
CREATE TABLE Transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    amount INT
);

INSERT INTO Transactions (customer_id, amount)
VALUES
    (101, 500),
    (101, 300),
    (102, 150);

table Transactions;

SELECT t1.customer_id, t1.amount
FROM Transactions t1
WHERE amount > (
    SELECT AVG(amount) FROM transactions t2
    WHERE t1.customer_id = t2.customer_id
);

-- sales
CREATE TABLE Sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    product VARCHAR(100),
    quantity INT,
    price_per_unit FLOAT(24),
    sales_date TIMESTAMP
);

INSERT INTO Sales (customer_id, product, quantity, price_per_unit, sales_date)
VALUES
    (101, 'Keyboard', 2, 25.00, '2024-04-01'),
    (102, 'Mouse', 1, 15.00, '2024-04-01'),
    (101, 'Monitor', 1, 200.00, '2024-04-02'),
    (103, 'Keyboard', 1, 25.00, '2024-04-02'),
    (101, 'Mouse', 3, 15.00, '2024-04-03');

table sales;

WITH total_sales AS (
    SELECT id, (quantity * price_per_unit) AS total FROM Sales
)
SELECT s.customer_id, ts.total, s.product
FROM Sales s
JOIN total_sales ts ON s.id = ts.id
WHERE s.product = 'Keyboard' AND ts.total > 30;

WITH total_sales AS (
    SELECT product, COUNT(id) as total_sold
    FROM Sales
    GROUP BY product
)
SELECT s.customer_id, s.product, ts.total_sold
FROM Sales s
JOIN total_sales ts ON s.product = ts.product
WHERE ts.total_sold = 1

-- test
CREATE TABLE Test_Products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    price INT
);

INSERT INTO Test_Products (name, price)
VALUES
    ('Laptop', 1000),
    ('Phone', 600),
    ('Table', 400);

CREATE TABLE Test_Sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT,
    quantity INT,

    FOREIGN KEY (product_id) REFERENCES Test_Products(id)
);

INSERT INTO Test_Sales (product_id, quantity)
VALUES
    (1, 5),
    (2, 10),
    (3, 7),
    (1, 3);

table Test_Products;
table Test_Sales;

-- cari total penjualan dari masing-masing product yang minimal terjual 7 unit
WITH total_sales AS (
    SELECT product_id, SUM(quantity) AS total_sold
    FROM Test_Sales
    GROUP BY product_id
)
SELECT tp.name, tp.price, ts.total_sold
FROM Test_Products tp
JOIN total_sales ts ON tp.id = ts.product_id
WHERE ts.total_sold >= 7;